server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useunicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  application:
    name: provider-client
eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/,http://eurekaserverone:8762/eureka/,http://eurekaservertwo:8763/eureka/
