server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useunicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true
  application:
    name: employee-msg-provider
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/,http://eurekaserverone:8762/eureka/,http://eurekaservertwo:8763/eureka/
  instance:
    instance-id: 员工信息服务-8083
    prefer-ip-address: true
logging:
  level:
    root: info


